# Generated by Django 3.0.5 on 2021-12-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=36, null=True)),
                ('model', models.CharField(max_length=12, null=True)),
                ('color', models.CharField(max_length=12, null=True)),
                ('jan_code', models.ImageField(upload_to='images')),
                ('image', models.ImageField(upload_to='mobile_pics')),
            ],
        ),
    ]
