# Generated by Django 3.0.5 on 2021-12-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='image',
            field=models.ImageField(blank=True, upload_to='mobile_pics'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='jan_code',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
