# Generated by Django 3.0.5 on 2021-12-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0002_auto_20211228_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='country_id',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='mobile',
            name='manufacturer_id',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='mobile',
            name='number_id',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
